---
services:
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./config/provisioning/:/etc/grafana/provisioning/
      - ./config/secrets:/etc/grafana/secrets
      - ./config/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/etc/grafana/secrets/admin_password
      - GF_SECURITY_ADMIN_USER_FILE=/etc/grafana/secrets/admin_user
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource
    secrets:
      - admin_password
      - admin_user
    networks:
      - grafana_network

secrets:
  admin_password:
    file: ./config/secrets/admin_password
  admin_user:
    file: ./config/secrets/admin_user

networks:
  grafana_network:
