apiVersion: 1
datasources:
## Opensearch

- orgId: 1
  name: opensearch-openstack-zuul
  type: grafana-opensearch-datasource
  access: proxy
  # Kibana: https://opensearch.logs.openstack.org/_dashboards/app/login
  url: https://opensearch.logs.openstack.org/
  basicAuth: true
  basicAuthUser: openstack
  basicAuthPassword: openstack
  withCredentials: true
  isDefault: false
  jsonData:
    database: logstash-logs-*
    flavor: opensearch
    maxConcurrentShardRequests: 5
    pplEnabled: true
    timeField: '@timestamp'
    version: 2.4.0
  version: 7
  editable: true

