apiVersion: 1
datasources:
  - name: opensearch-rdoproject-zuul
    type: grafana-opensearch-datasource
    access: proxy
    url: https://opensearch.rdoproject.org/elasticsearch
    basicAuth: true
    basicAuthUser: kibana_rdoproject_org
    basicAuthPassword: rdoproject_org
    withCredentials: true
    isDefault: true
    jsonData:
      database: zuul.rdoproject.org-*
      timeField: '@timestamp'
      version: 2.11.1
      flavor: 'opensearch'
      maxConcurrentShardRequests: 5
    secureJsonData:
      basicAuthPassword: rdoproject_org
      xpack: true
    version: 7