"apiVersion": "apps/v1"
"kind": "Deployment"
"metadata":
  "name": "webserver-deployment"
"spec":
  "replicas": 3
  "selector":
    "matchLabels":
      "app": "nginx"
  "template":
    "metadata":
      "labels":
        "app": "nginx"
    "spec":
      "containers":
      - "image": "nginx:latest"
        "livenessProbe":
          "httpGet":
            "path": "/"
            "port": 80
        "name": "nginx"
        "ports":
        - "containerPort": 80
